### ISSUE TITLE
Variables are not allowed to begin as numbers

### ISSUE THREAD

**Issue by Alquemar** [JackCasfren/ForPassJS#2]
# Issue
Variables are not able to be submitted if they begin as numbers characters in both input texts.

# Images
![1](https://github.com/user-attachments/assets/205b0271-6f56-4c4c-bc6f-eba62cfefa4f)\
![2](https://github.com/user-attachments/assets/a93c72ec-fce7-4fda-b426-ad08463ba581)

**Comment by JackCasfren** [comment]
Greetings Alquemar,

We have reviewed your issue and will proceed to fix it effective immediately.

**Comment by JackCasfren** [comment]
We where able to replicate the issue and found that it originates from this:

```
    if (resultDiv.querySelector(`#${inputValue}`)) {
        console.log("Button with the same ID already exists inside the result div.");
        return;
    }
```

    
The main issue seems that querySelector does like #number so after consulting with experts (Claude.ia this time)
I concluded that the best option is to have a prefix.

```button.id = "ID-" + inputValue;```

so now every time querySelector is used, it is done with the "ID-" prefix.

querySelector(\`#ID-${inputValue}\`)

I don't know if this is decent. But it works, and if it works, its less stupid than it not working.
